---
- hosts: coreos
  gather_facts: False
  roles:
    - defunctzombie.coreos-bootstrap

  tasks:
    - name: mask locksmithd
      systemd:
        name=locksmithd.service
        enabled=no
        masked=yes
        state=stopped

    - name: ensure update-engine.service
      systemd:
        name=update-engine.service
        enabled=yes
        masked=no
        state=started

